Workaround dev dependencies install issue on travis CI
  Installing uh-wm (0.2.1)
  ERROR:  While executing gem ... (Gem::InstallError)
  uh-wm requires uh-layout (>= 0.4.2, ~> 0.4)